version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: social-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    container_name: social-mailhog
    ports:
      - "1025:1025"   # SMTP server
      - "8025:8025"   # Web UI

  redis:
    image: redis:7-alpine
    container_name: social-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:
